[project]
name = "slack-search-mcp"
version = "0.1.0"
dependencies = [
    "shared",
    "mcp[fastapi]>=1.13.1",
    "fastapi>=0.115.0",
    "uvicorn>=0.35.0",
    "google-cloud-bigquery>=3.20.0",
    "google-genai>=0.1.0",
    "python-dotenv>=1.0.1",
    "slack-sdk>=3.39.0",
    "google-auth>=2.0.0"
]

[tool.setuptools]
package-dir = {"" = "."}
packages = []
